#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
feh --bg-scale $HOME/Photos/.wallpaper_current


# Scratchpad
if [[ $(xdotool search --class scratchpad) == "" ]]; then 
  # Stops multiple scratchpads from being created
  st -c scratchpad &
fi

# Floating Applications
bspc rule -a feh state=floating
bspc rule -a scratchpad sticky=on state=floating #hidden=on

# Configuration
if  xrandr | grep "$EXTERNAL_MONITOR connected"; then
  bspc monitor $LOCAL_MONITOR -d 1 2 3
  bspc monitor $EXTERNAL_MONITOR -d 4 5 6
else
  bspc monitor $LOCAL_MONITOR -d 1 2 3 4 5 6
fi

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


